### PR TITLE
feat: support export * without as

### LINKED ISSUE #124: Support export * without as
I really wish to be able to use `export * from 'foo'`. By looking at implemented [tests](https://github.com/unjs/unimport/blob/main/test/to-export.test.ts), I assume this is currently not possible. It doesn't seem like a rare use-case, and as `as` is already optional, I don't see a reason to not support it.

### PR DESCRIPTION
**Pull request by kvcvc**
Fix #124.

### CODE REVIEW

**Comment by antfu** [comment]
Emm, this does not seem right. While yet is might work with `toExports`, most of the time, `unimport` is to used with `injectImports` (auto imports). For auto import to work, we need to know the names of the APIs to be imported at build time. Meaning importing from `*` won't work.

**Comment by kvcvc** [comment]
Ah, I wanted make use of it in Nuxt with auto imports, figured it was enough to export from the generated imports file in .nuxt directory. Did not know they are purposely to be named.

**Comment by antfu** [comment]
While yes using `export * from`, TypeScript can infer the exports for your IDE to show up the list, but `unimport` can't know that. That means it offers you a fake situation where you can see the type, but they are not actually been auto imported.

**Comment by kvcvc** [comment]
Well, that is a shame.

**Pull request closed without merging**
